import { BadgeCheck, Sparkles } from "lucide-react";
import type { FranchiseSource } from "../../engine/types.js";
import "./SourceBadge.css";

interface SourceBadgeProps {
  source?: FranchiseSource;
}

/**
 * Distinguishes hand-curated franchises from ones auto-generated by an
 * AniList crawl. Deliberately does NOT use the destructive/red treatment —
 * "anilist-generated" is an honesty disclosure about provenance, not an
 * error state.
 */
export function SourceBadge({ source }: SourceBadgeProps) {
  const isCurated = source === undefined || source === "curated";

  if (isCurated) {
    return (
      <span className="source-badge source-badge--curated">
        <BadgeCheck aria-hidden="true" size={13} />
        Curated
      </span>
    );
  }

  return (
    <span className="source-badge source-badge--generated">
      <Sparkles aria-hidden="true" size={13} />
      Auto-generated from AniList — unverified
    </span>
  );
}
